config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "tours#index"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :tours, only: %i(index show)
    resources :users, only: %i(new create)
    resources :book_tours, only: %i(index create)
    namespace :admin do
      resources :book_tours, only: %i(index update destroy)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_tour.rb
class BookTour < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  enum status: {wait: 0, accept: 1, begin: 2, close: 3}
  belongs_to :user
  belongs_to :tour
  validates :quantity, presence: true,
    numericality: {greater_than: Settings.min_quantity}
  validates :email, presence: true,
    format: {with: VALID_EMAIL_REGEX},
    length: {maximum: Settings.user.email.max_length}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :customer_name, presence: true
  validates :phone_number, presence: true
  before_create :date_start
  validate :date_end
  delegate :title, to: :tour
  delegate :name, to: :user
  scope :active, ->{where(deleted: false)}
  scope :newest, ->{active.order(created_at: :desc)}

  def date_end
    return if end_date >= start_date

    errors.add(:end_date, I18n.t("err_day_end"))
  end

  def date_start
    return if start_date > Time.zone.today

    errors.add(:start_date, I18n.t("err_day_start"))
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :book_tours, dependent: :destroy
  belongs_to :tour_type
  scope :tours_Highlight, ->{joins(:book_tours).group(:tour_id).last(4)}
  scope :newest, ->{order(created_at: :desc)}
  scope :search_tour, (lambda do |key|
    where("title like ? or location like ?", "#{key}%", "#{key}%")
  end)
end

app/models/tour_type.rb
class TourType < ApplicationRecord
  has_many :tours, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :book_tours, dependent: :destroy
  has_many :reviews, dependent: :destroy
  enum role: {admin: 1, user: 0}

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create string, cost: cost
  end

  has_secure_password
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin"
  before_action :require_admin

  def require_admin
    return if current_user&.admin?

    flash[:notice] = t "admin_fail"
    redirect_to root_path
  end
end

app/controllers/admin/book_tours_controller.rb
class Admin::BookToursController < Admin::AdminController
  before_action :find_book_tour, only: %i(update destroy)

  def index
    @book_tours = BookTour.newest
                          .paginate(page: params[:page],
      per_page: params[:per_page] || Settings.user.panigate_size)
  end

  def update
    ActiveRecord::Base.transaction do
      @book_tour.status = params[:status].to_i
      if @book_tour.save
        flash[:success] = t "update_success"
      else
        flash[:error] = t "update_error"
      end
      redirect_to admin_book_tours_path
    end
  rescue ArgumentError
    flash[:error] = t "update_error"
    redirect_to admin_book_tours_path
  end

  def destroy
    if @book_tour.update_column(:deleted, Settings.user.deleted)
      MailerMailer.send_email_user(@book_tour).deliver
      flash[:success] = t "remove_tour_success"
    else
      flash[:error] = t "remove_tour_error"
    end
    redirect_to admin_book_tours_path
  end

  private

  def find_book_tour
    @book_tour = BookTour.find_by(id: params[:id])
    return if @book_tour

    flash[:notice] = t "tour_not_found"
    redirect_to admin_book_tours_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  include SessionsHelper

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else
                    I18n.default_locale
                  end
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = t "login_message"
    redirect_to login_path
  end

  def paginate model
    model.paginate(page: params[:page],
      per_page: params[:per_page] || Settings.user.panigate_size)
  end
end

app/controllers/book_tours_controller.rb
class BookToursController < ApplicationController
  before_action :logged_in_user, only: %i(index create)
  before_action :load_user_book_tours, only: :index

  def index; end

  def create
    @book_tour = current_user.book_tours.new book_tour_params
    @book_tour.price_tour = total_price
    respond_to do |format|
      if @book_tour.save
        format.html{redirect_to @book_tour, message: t("booking_sucsses")}
      else
        format.html{render :new}
      end
      format.js
    end
  end

  private

  def book_tour_params
    params.require(:book_tour).permit :tour_id,
                                      :quantity, :start_date, :end_date,
                                      :customer_name, :phone_number, :email
  end

  def load_user_book_tours
    @book_tours = current_user.book_tours.includes(:tour)
  end

  def total_price
    number = params[:book_tour][:quantity].to_i
    price = @book_tour.tour.price
    number * price
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      flash[:success] = t "login_true"
      log_in user
      redirect_to root_path
    else
      flash[:danger] = t "login_fail"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, only: :show
  before_action :search, only: :index
  def index
    @tourhighlights = Tour.tours_Highlight
  end

  def show
    @book_tour = BookTour.new
  end

  private

  def find_tour
    @tour = Tour.find_by(id: params[:id])
    return if @tour

    flash[:error] = t "not_find_tour"
    redirect_to root_path
  end

  def search
    tours = if params[:key].blank?
              Tour
            else
              Tour.search_tour(params[:key])
            end.newest
    @tours = paginate tours
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "register_success"
      redirect_to users_path
    else
      flash[:danger] = t "register_error"
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :phone_number, :password,
                                 :password_confirmation
  end
end

app/helpers/book_tours_helper.rb
module BookToursHelper
  def count num1, num2 = 1
    num1 + num2
  end

  def value_select_tag
    [[t("wait"), Settings.user.wait],
      [t("accept"), Settings.user.accept], [t("begin"),
        Settings.user.begin], [t("close"), Settings.user.close]]
  end
end

app/helpers/counter_helper.rb
module CounterHelper
  def count_stt num1, num2
    (num1 - 1) * Settings.user.panigate_size + num2 + 1
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/view_admin_helper.rb
module ViewAdminHelper
  def selected status
    case status
    when BookTour.statuses.key(0)
      Settings.user.wait
    when BookTour.statuses.key(1)
      Settings.user.accept
    when BookTour.statuses.key(2)
      Settings.user.begin
    when BookTour.statuses.key(3)
      Settings.user.close
    end
  end
end

app/views/admin/book_tours/_book_tour.html.erb
<tr>
  <th scope="row"><%= count_stt(params[:page] ? params[:page].to_i : 1, book_tour_counter) %></th>
  <td><%= book_tour.title %></td>
  <td><%= book_tour.customer_name %></td>
  <td><%= book_tour.phone_number %></td>
  <td><%= book_tour.start_date %></td>
  <td><%= book_tour.end_date %></td>
  <%= form_tag admin_book_tour_path(book_tour), method: :patch do %>
    <td>
      <%= select_tag :status, options_for_select(value_select_tag, selected(book_tour.status)),
        onchange: "this.form.submit();", disabled: book_tour.close? %>
    </td>
  <% end %>
  <td><%= book_tour.created_at %></td>
  <td>
    <td><%= link_to t("delete"), admin_book_tour_path(book_tour),
      method: :delete, class: "btn btn-danger" %></td>
  </td>
</tr>

app/views/admin/book_tours/index.html.erb
<div class="container-admin">
  <div class="user-content">
    <div class="user-content-table">
      <div class="content-table-container">
        <h1 class="content-table-container-header">
          <%= t("list_book_tour") %>
        </h1>
        <div class="content-table-container-list">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>STT</th>
                <th><%= t("title_tour") %></th>
                <th><%= t("customer_name") %></th>
                <th><%= t("customer_phone") %></th>
                <th><%= t("tour_start") %></th>
                <th><%= t("tour_end") %></th>
                <th><%= t("status") %></th>
                <th><%= t("create_at") %></th>
                <th colspan="2"></th>
              </tr>
            </thead>
            <tbody>
              <%= render @book_tours %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<p><%= will_paginate @book_tours %></p>

app/views/admin/layouts/_menu_admin.html.erb
<div class="menu-user-left">
  <div class="user-left-nav">
    <div class="user-left-nav-name">
      <a href="">
        <img class="user-left-nav-img" src="" style="width: 50px; height: 50px;" />
      </a>
      <span><%= current_user.name %></span>
    </div>
  </div>
  <div class="user-left-items">
    <h4 class="user-left-item-title">
      <%= t("setting") %>
    </h4>
    <%= link_to t("update_user"), "#", class: "user-left-item" %>
    <%= link_to t("password"), "#", class: "user-left-item" %>
    <%= link_to t("logout"), "#", class: "user-left-item" %>
  </div>
  <div class="user-left-items">
    <h4 class="user-left-item-title">
      <%= t("tour") %>
    </h4>
    <%= link_to t("list_tour"), "#", class: "user-left-item" %>
    <%= link_to t("add_tour"), "#", class: "user-left-item" %>
    <%= link_to t("statistical"), "#", class: "user-left-item" %>
  </div>
</div>

app/views/book_tours/_book_tour.html.erb
<tr>
  <th scope="row"><%= book_tour_counter + 1 %></th>
  <td><%= link_to book_tour.title, tour_path(book_tour) %></td>
  <td><%= book_tour.quantity %></td>
  <td><%= l(book_tour.start_date, format: :default) %></td>
  <td><%= l(book_tour.end_date, format: :default) %></td>
  <td><%= book_tour.status %></td>
</tr>

app/views/book_tours/create.js.erb
<% if @book_tour.errors.any? %>
   alert('<%= @book_tour.errors.full_messages.first %>')
<% else %>
   alert('<%= t("booking_sucsses") %>')
<% end %>

app/views/book_tours/index.html.erb
<div class="book_tour_wrap">
  <h1 class="book_tour_title">
    <%= t("your_tour") %>
  </h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">STT</th>
        <th scope="col"><%= t("tour_name") %></th>
        <th scope="col"><%= t("person") %></th>
        <th scope="col"><%= t("tour_start") %></th>
        <th scope="col"><%= t("tour_end") %></th>
        <th scope="col"><%= t("status") %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @book_tours %>
    </tbody>
  </table>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header_wrap">
    <div class="logo_nav">
      <a href="" class="logo_nav_link">Travel</a>
    </div>
    <div class="nav_item">
      <%= link_to t("home"), "/", class: "nav_item_link" %>
      <%= link_to t("tour"), "/", class: "nav_item_link" %>
      <%= link_to t("about"), "/about", class: "nav_item_link" %>
      <%= link_to t("contact"), "/contact", class: "nav_item_link" %>
      <% if logged_in? %>
        <%= link_to t("logout"), logout_path, method: :delete, class: "nav_item_link" %>
      <% else %>
        <%= link_to t("login"), login_path, class: "nav_item_link" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_slider.html.erb
<div class="slider">
  <div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active slider_tour ">
        <img class="carousel-image" src="/images/image1.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item slider_tour">
        <img class="carousel-image" src="/images/image2.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item slider_tour">
        <img class="carousel-image" src="/images/image3.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("title") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap",
     media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <section class="content flash_message" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="content_flash">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
      <%= render "shared/error_messages" %>
    </section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-2">
          <%= render "layouts/menu_admin" %>
        </div>
        <div class="col-lg-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("title") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap",
     media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row content_message">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
      <%= render "shared/error_messages" %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @object %>
  <% if @object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= t "form_message" %>
        <%= t("count_err", count: @object.errors.count) %>
      </div>
      <ul>
        <% @object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/tour/show.html.erb
<div class="content_detail">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="tour_content">
            <div class="tour_detail_title">
              <div class="tour_detail_title_left">
                <p class="title_left_location">da nang</p>
                <h4 class="title_left_name">Tour di ngang da nang</h4>
                <div class="title_left_wrap">
                  <div class="icon_wrap">
                    <i class="fas fa-users"></i>
                    <span>2 <%= t("tour_person") %></span>
                  </div>
                  <div class="icon_wrap">
                    <i class="far fa-clock"></i>
                    <span>2 <%= t("tour_day") %></span>
                  </div>
                </div>
              </div>
              <div class="tour_detail_title_right">
                <h3>$999</h3>
              </div>
            </div>
           <div class="tour_img_wrap">
            <img src="/images/image3.jpg" alt="" class="img_tour">
           </div>
            <div class="tour_descripton">
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum possimus eius omnis tenetur incidunt animi odio nisi nobis! Reprehenderit aut rerum fugiat perspiciatis vero adipisci nostrum obcaecati delectus quibusdam neque?
              Natus, suscipit. Saepe temporibus at eaque autem cum nemo, quos, similique natus, fugiat optio vitae ex incidunt enim sint asperiores tenetur exercitationem! Ad reiciendis quos inventore nesciunt error aspernatur ut.
              </p>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum possimus eius omnis tenetur incidunt animi odio nisi nobis! Reprehenderit aut rerum fugiat perspiciatis vero adipisci nostrum obcaecati delectus quibusdam neque?
                Natus, suscipit. Saepe temporibus at eaque autem cum nemo, quos, similique natus, fugiat optio vitae ex incidunt enim sint asperiores tenetur exercitationem! Ad reiciendis quos inventore nesciunt error aspernatur ut.
              </p>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="form_book_tour">
            <h5><%= t("tour_tel") %> (028) 3933 8002</h4>
            <%= form_for @book_tour, html: {class: "form_book"} do |f| %>
              <%= f.hidden_field :tour_id, :value => 1 %>
              <%= f.hidden_field :tour_day, :value => 5 %>
              <div class="form_book_group">
                  <%= f.label :start_date, t("tour_start"), class: "label_time" %>
                  <%= f.text_field :start_date, required: true %>
              </div>
              <div class="form_book_group">
                  <%= f.label :end_date, t("tour_end"), class: "label_time" %>
                  <%= f.text_field :end_date, required: true %>
              </div>
              <div class="form_book_group">
                  <%= f.label :quantity, t("tour_quatity"), class: "label_time" %>
                  <%= f.number_field :quantity, required: true, min: 1, max: 5 %>
              </div>
              <div class="form_book_group">
                  <%= f.label :customer_name, t("customer_name"), class: "label_time" %>
                  <%= f.text_field :customer_name, required: true %>
              </div>
              <div class="form_book_group">
                  <%= f.label :phone_number, t("phone"), class: "label_time" %>
                  <%= f.telephone_field :phone_number, required: true, pattern: "[0-9]{4}[0-9]{3}[0-9]{3}",
                   placeholder: "0854-083-118" %>
              </div>
              <div class="form_book_group">
                  <%= f.label :email, t("email"), class: "label_time" %>
                  <%= f.email_field :email, required: true%>
              </div>
              <div class="form_book_group_price">
                  <span class="label_time" for="datetimepicker" ><%= t("tour_price") %></span>
                  <span id="tour_price">4190000</span>
                </div>
                <p id="total_price" class="total_price_tour">12.570.000 VND</p>
              <%= f.submit t("tour_book"), class: "btn_submit_book" %>
          <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="container bootstrap snippets bootdey comment_wrap">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">
                    <%t("recent_coment")%></h3>
                <span class="label label-info">
                  <%= t("sum_comment",count: 5) %>
                </span>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="img-circle img-responsive img-user" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="#">
                                        Google Style Login Page Design Using Bootstrap</a>
                                    <div class="mic-info">
                                        <%= t("by") %> <a href="#">Bhaumik Patel</a> <%= t("on") %> 2 Aug 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Awesome design
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                      <%= t("like") %>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                      <%= t("comment") %>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                      <%= t("remove") %>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="img-circle img-responsive img-user" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="#">Admin Panel Quick Shortcuts</a>
                                    <div class="mic-info">
                                        <%= t("by") %> <a href="#">Bhaumik Patel</a> <%= t("on") %> 11 Nov 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                    euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                      <%= t("like") %>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                      <%= t("comment") %>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                      <%= t("remove") %>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="https://bootdey.com/img/Content/avatar/avatar6.png" class="img-circle img-responsive img-user" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="#">Cool Sign Up</a>
                                    <div class="mic-info">
                                        <%= t("by") %> <a href="#">Bhaumik Patel</a> <%= t("on") %> 11 Nov 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                    euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary " title="Edit">
                                      <%= t("like") %>
                                    </button>
                                    <button type="button" class="btn btn-success " title="Approved">
                                      <%= t("comment") %>
                                    </button>
                                    <button type="button" class="btn btn-danger " title="Delete">
                                      <%= t("remove") %>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <div class="input_comment">
                  <textarea id="user_commented" >
                  </textarea>
                  <button type="button" class="btn btn-primary btn_comment">
                    <%= t("comment") %>
                  </button>
                </div>
                <a href="#" class="btn btn-info btn-sm btn-block" role="button"><span class="glyphicon glyphicon-refresh"></span> <%= t("more") %></a>
            </div>
        </div>
    </div>
  </div>

app/views/tours/_tour.html.erb
<div class="col-lg-6 mb-4">
  <%= link_to tour_path(tour), class: "link_card" do  %>
    <div class="card_wrap">
      <div class="row">
        <div class="col-lg-5 card_wrapper">
          <img class="img_card" src="/images/card_1.jpg">
        </div>
        <div class="col-lg-7 card_wrapper">
          <div class="card_content">
            <h4><%= tour.title %></h4>
            <p><%= t("tour_day", count: tour.day) %>, <%= t("tour_night", count: tour.day) %></p>
            <div class="card_content_price">
              <span class="price_text"><%= t("tour_start") %></span>
              <span class="price_number"><%= tour.price %></span>
            </div>
            <div class="card_content_des">
              <%= tour.description %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/_tourhighlight.html.erb
<div class="col-lg-6 mb-4">
  <%= link_to tour_path(tour), class: "link_card" do  %>
    <div class="card_wrap">
      <div class="row">
        <div class="col-lg-5 card_wrapper">
          <img class="img_card" src="/images/card_1.jpg">
        </div>
        <div class="col-lg-7 card_wrapper">
          <div class="card_content">
            <h4><%= tour.title %></h4>
            <p><%= t("tour_day", count: tour.day) %>, <%= t("tour_night", count: tour.day) %></p>
            <div class="card_content_price">
              <span class="price_text"><%= t("tour_start") %></span>
              <span class="price_number"><%= tour.price %></span>
            </div>
            <div class="card_content_des">
              <%= tour.description %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/index.html.erb
<%= render "layouts/slider" %>
<div class="content_wrap">
  <div class="container">
    <h1 class="title_content"><%= t("tour_title") %></h1>
    <%= form_tag tours_path, method: "GET", class: "form_search_tour" do %>
      <%= text_field_tag :key, "", class: 'input_location', placeholder: t("tour_placeholder"), value: params[:key].present? ? params[:key] : "" %>
      <%= button_tag t("tour_search"), class: "btn_search" %>
    <% end %>
    <h3 class="title_support">
      <%= t("tour_often") %>
    </h3>
    <div class="row mb-4">
      <% if @tours.size > Settings.min_quantity %>
        <%= render @tours %>
      <% else %>
        <%= t("not_find_tour") %>
      <% end %>
    </div>
    <p><%= will_paginate @tours %></p>
    <h3 class="title_support">
      <%= t("tour_hot") %>
    </h3>
    <div class="row mb-4">
      <%= render @tourhighlights %>
    </div>
  </div>
</div>